version: "3"

services:
  nginx:
    ports:
      - "3000:80"

  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=rubens
      - MONGO_PASSWORD=rubens
      - SESSION_SECRET='im a patata'
    command: npm run dev

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rubens
      - MONGO_INITDB_ROOT_PASSWORD=rubens